import Image from 'next/image'
import classes from '@/app/skill/skill.module.scss'
import { Footer } from '../componets/Footer';
import Header from '../componets/Header';
import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Shota`s Skill',
  description: 'Generated by create next app',
}

export default function Skill() {
  return (
    < >
      <Header />

      <h2 className={classes.ttl}>Programming Languages</h2>
      <ul className={classes.programmingLans}>
        <li>
          <Image src="/html_icon.png" alt="" width={200} height={200}/>
          <p>2022年10月～<br />
            実務経験あり
          </p>
        </li>
        <li>
          <Image src="/css_icon.png" alt="" width={200} height={200}/>
          <p>2022年10月～<br />
            実務経験あり
          </p>
        </li>
        <li>
          <Image src="/javascript_icon.png" alt="" width={200} height={200}/>
          <p>2023年6月～<br />
            実務経験あり
          </p>
        </li>
      </ul>

      <h2 className={classes.ttl}>Flame Works</h2>
      <ul className={classes.flameWorks}>
      <li>
          <Image src="/react_icon.png" alt="" width={200} height={200}/>
          <p>2023年8月～
          </p>
        </li>
        <li>
          <Image src="/nextjs_icon.png" alt="" width={200} height={200}/>
          <p>2023年8月～
          </p>
        </li>
      </ul>

      <h2 className={classes.ttl}>Development Tools</h2>
      <ul className={classes.devTools}>
        <li>
            <Image src="/vscode_icon.png" alt="" width={200} height={200}/>
            <p>2022年10月～<br />
            実務経験あり
            </p>
        </li>

        <li>
          <Image src="/github_icon.png" alt="" width={200} height={200}/>
          <p>2023年6月～<br />
          Githubアカウント: <br /><Link href="https://github.com/Muu0215" className={classes.devTools__text}>github.com/Muu0215</Link>
          </p>
        </li>
      
        <li>
            <Image src="/figma_icon.png" alt="" width={200} height={200}/>
            <p>2023年4月～<br />
            実務経験あり
            </p>
        </li>

        <li>
            <Image src="/photoshop_icon.png" alt="" width={200} height={200}/>
            <p>2021年4月～<br />
            実務経験あり
            </p>
        </li>

      </ul>

      <Footer />



    </>
  )
}
