import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './reset.css'
import './globals.css'
import { GiSonicShoes } from "react-icons/gi";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Shota`s Profile',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}