import Image from 'next/image'
import Header from '../componets/Header';
import classes from '@/app/input/input.module.scss'
import Link from 'next/link';
import { Footer } from '../componets/Footer';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Shota`s Input',
  description: 'Generated by create next app',
}

export default function Contact() {
  return (
    < >
      <Header />
      <h2 className={classes.ttl}>Service</h2>
      <div>
        <ul className={classes.service}>
          <li>
            <Image src="/progate_icon.png" alt='' width={300} height={100}/>
          </li>
          <li>
            <Image src="/paiza_icon.png" alt='' width={300} height={100}/>
          </li>
          <li>
            <Image src="/qiita_icon.png" alt='' width={300} height={100}/>
          </li>
        </ul>

        <h2 className={classes.ttl}>Books</h2>
        <ul className={classes.service}>
          <li>
            <Image src="/book1.jpg" alt='' width={200} height={300}/>
          </li>
          <li>
            <Image src="/book2.jpg" alt='' width={200} height={300}/>
          </li>
          <li>
            <Image src="/book3.jpg" alt='' width={200} height={300}/>
          </li>
        </ul>

      </div>

      <Footer />
    </>
  )
}
